### ISSUE TITLE
Drag and drop upload isn't styled in an obvious way and doesn't work

### ISSUE THREAD

**Issue by GraysonE** [ErhardLabs/tunefuze#135]

**Comment by erhardsc** [comment]
@GraysonE 

Drag and drop upload works again and I added better styles.

I still can't get the `dragexit` or even `dragleave` to remove the drop area though. There's an [interesting solution here](https://stackoverflow.com/questions/10867506/dragleave-of-parent-element-fires-when-dragging-over-children-elements) but it involves setting each pointer event to none that is a child of the drag event. We are currently setting the drag event on the `html` tag so setting the pointer event to none on each sub item of the `html` tag is a bad idea. 

I'm going to leave this for now
