### ISSUE TITLE
Visualizer Settings

### ISSUE THREAD

**Issue by GraysonE** [ErhardLabs/tunefuze#141]
https://sketch.cloud/s/agE1z/a/jq1AL9

**Comment by GraysonE** [comment]
@erhardsc Visualizer settings need an indicator that shows which visualizer is selected.

**Comment by GraysonE** [comment]
- [ ] Add foreign key

**Comment by erhardsc** [comment]
@GraysonE 

I added styes to the visualizer settings and got the color picker added and saving to the database. The color picker values will need to be hooked up to the visualizers though.

**Comment by erhardsc** [comment]
@GraysonE 

All is working now!

**Comment by GraysonE** [comment]
- [ ] Color picker works for "Circles" visualizer.
