### ISSUE TITLE
Following/Follower styles

### ISSUE THREAD

**Issue by GraysonE** [ErhardLabs/tunefuze#151]
- [x] Following list styles

- [x] Followers list styles

- [ ] After following a user the notification that comes up underneath the profile photo needs a little margin.

**Comment by erhardsc** [comment]
@GraysonE 

I updated the following/followers styles but I didn't see any notification popup. I did add some margin to the notifications in this PR though https://github.com/ErhardLabs/tunefuze/pull/179
