### ISSUE TITLE
Fuze settings dropdown within Fuze edit page styles

### ISSUE THREAD

**Issue by GraysonE** [ErhardLabs/tunefuze#183]

**Comment by GraysonE** [comment]
![Screen Shot 2020-02-20 at 8 44 34 PM](https://user-images.githubusercontent.com/7062755/75002580-271c2a80-5422-11ea-900d-94a407ac3e7b.png)

**Comment by erhardsc** [comment]
Fixed in this commit

https://github.com/ErhardLabs/tunefuze/pull/188/commits/2e298bd591fe328ec6f0afcd8c3173bcb4286107
