### ISSUE TITLE
Improved Search UX

### ISSUE THREAD

**Issue by GraysonE** [ErhardLabs/tunefuze#269]

**Comment by GraysonE** [comment]
@erhardsc please fix the styles for the search page. The "user-group" class in 'search-loop.php' is what's making those fuzes look like that. 
![Screen Shot 2020-03-10 at 8 03 09 PM](https://user-images.githubusercontent.com/7062755/76374993-54b21080-630a-11ea-9a53-051a2193b84d.png)

**Comment by erhardsc** [comment]
@GraysonE 

Had to go with a list view for the UI. It's the quickest way to get the frontend to work until we go back into a design phase with this
