### ISSUE TITLE
Profile - About

### ISSUE THREAD

**Issue by erhardsc** [ErhardLabs/tunefuze#28]
[Desktop](https://sketch.cloud/s/agE1z/zxa9Z8b)

[Mobile](https://sketch.cloud/s/agE1z/ZOmGRJp)

**Comment by erhardsc** [comment]
@GraysonE - There is currently not an option for me to add the bio so the bio shows up blank for me

**Comment by GraysonE** [comment]
https://trello.com/c/22yiVYwZ

**Comment by GraysonE** [comment]
@Spessartine Sumner and I were discussing the about page and how bare bones it is. Do you want to make this more exciting or keep it simple like it is currently?

**Comment by GraysonE** [comment]
I need to make the edit bio and location fields dynamic, not database-based.

**Comment by erhardsc** [comment]
@GraysonE The about page does not have dynamic content in it still.

Also, the location is not being set in the correct place. I'm going to link #23 since this will effect that issue as well

**Current site:**
![Screen Shot 2019-12-04 at 4 12 17 PM](https://user-images.githubusercontent.com/17289312/70189577-e6c5cf80-16b0-11ea-8d04-9c154d889195.png)

**Design:**
![Screen Shot 2019-12-04 at 4 13 03 PM](https://user-images.githubusercontent.com/17289312/70189605-f9d89f80-16b0-11ea-870b-c2e9c3271e7e.png)

**Comment by GraysonE** [comment]
- [ ] Create stats functionality
