### ISSUE TITLE
Profile - Notifications

### ISSUE THREAD

**Issue by erhardsc** [ErhardLabs/tunefuze#29]
https://sketch.cloud/s/agE1z/xrmqdgV

**Comment by erhardsc** [comment]
@GraysonE - I'm able to view other users notifications when viewing their profile

![Screenshot 2019-05-22 16 07 44](https://user-images.githubusercontent.com/17289312/58212533-51cb2e00-7cac-11e9-8ae3-af5c3469bbcd.png)

**Comment by erhardsc** [comment]
@GraysonE - Please match the content in the notifications to the content in the design

![Screenshot 2019-05-23 16 47 39](https://user-images.githubusercontent.com/17289312/58291424-98875980-7d7a-11e9-9291-0465b7323de5.png)

**Comment by erhardsc** [comment]
@GraysonE 

There is still some backend content that will need to be added in order for me to finish the styles

The function `bp_the_notification_description()` is preventing me from adding a font weight to the name of the user who is in the notification.
<img width="952" alt="Screen Shot 2019-12-06 at 4 35 13 PM" src="https://user-images.githubusercontent.com/17289312/70363638-6b962200-1846-11ea-8704-61373d739554.png">

![Screen Shot 2019-12-06 at 4 37 51 PM](https://user-images.githubusercontent.com/17289312/70363723-caf43200-1846-11ea-83a0-d608a6d3cf47.png)


Also, for the time since notification happened lets stick to just one line of text instead of what is currently being shown. For example:

6 months, and 2 weeks

Should just be

6 months

**Comment by GraysonE** [comment]
@erhardsc make sure when you go to style this that you use new notifications for follow and like as old one's will not have the proper formatting.

**Comment by erhardsc** [comment]
@GraysonE 

Styles have been updated and also mobile styles were updated

**Comment by GraysonE** [comment]
@erhardsc mobile styles should have names and fuzes in bold.
