### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by erhardsc** [ErhardLabs/tunefuze#31]
The dashboard with have two different views:

All of the sections are detailed in the designs

[Signed in](https://sketch.cloud/s/agE1z/bgRwZr0)

[Signed out](https://sketch.cloud/s/agE1z/8ynLOV3)

**Comment by erhardsc** [comment]
@GraysonE - The dashboard show more buttons are all clustered at the bottom instead of being attached to their associated div. Please fix when you can.

![Screenshot 2019-06-10 15 50 36](https://user-images.githubusercontent.com/17289312/59229397-84739280-8b97-11e9-86f2-497c05883676.png)

**Comment by GraysonE** [comment]
@erhardsc the branch I worked on is issue_31.1. This is done now :)

**Comment by GraysonE** [comment]
@erhardsc the branch I worked on is issue_31.1. This is done on my part now :)

**Comment by erhardsc** [comment]
- [ ] Add more spacing to header items

**Comment by erhardsc** [comment]
@GraysonE 

[ ] - Add import statement to show a bunch of test fuzes in the dashboard for further testing of the UI and styles

**Comment by GraysonE** [comment]
- [ ] Get logged out user fuze previews

**Comment by GraysonE** [comment]
@erhardsc let's just make sure we're exporting the tunefuze site to one another. I made a lot of fuzes recently.
