### ISSUE TITLE
Search Feature

### ISSUE THREAD

**Issue by erhardsc** [ErhardLabs/tunefuze#32]
[Search with results](https://sketch.cloud/s/agE1z/My3qKmb)

[Search with no results](https://sketch.cloud/s/agE1z/523p4np)

**Comment by erhardsc** [comment]
SELECT * FROM `tf_fuzes` WHERE title LIKE '%$search_term%' SEARCH_LIMIT $limit OFFSET $offset;

$limit is a constant
$offset is a variable

define('SEARCH_LIMIT', 12);

pagination init: $offset = 0;
pagination equation: $offset += SEARCH_LIMIT;

**Comment by erhardsc** [comment]
@GraysonE 

What needs to be done with this? The design got changes to a toggle between users and fuzes which is already implemented on the site.

<img width="1001" alt="Screen Shot 2019-12-12 at 12 47 11 PM" src="https://user-images.githubusercontent.com/17289312/70743698-8f8db380-1cdd-11ea-9a03-f1bac3020ece.png">

**Comment by erhardsc** [comment]
@GraysonE the search for users should search both the name and the username

**Comment by erhardsc** [comment]
@GraysonE getting errors on fuzes for the like count

![Screen Shot 2020-01-20 at 5 06 02 PM](https://user-images.githubusercontent.com/17289312/72764898-30a63e80-3ba7-11ea-9d85-5e55442715b4.png)

**Comment by erhardsc** [comment]
@GraysonE 

- [ ] cache the query for getting activity likes total count

**Comment by GraysonE** [comment]
@erhardsc decided against caching the activity likes query because it's too dynamic. If we were literally using the same query every time it would make sense.

**Comment by GraysonE** [comment]
@erhardsc please style the fuze dropdown on this page. It changed because I consolidated every "get fuze" occurrence into one place. This will make everything super consistent from now on.

**Comment by erhardsc** [comment]
@GraysonE 

Fuze styles have been updated and I made some style tweaks to the search page as well
