### ISSUE TITLE
Dashboard - Add to curated

### ISSUE THREAD

**Issue by erhardsc** [ErhardLabs/tunefuze#33]
@Spessartine @GraysonE the dashboard add to curated feature will have a pop-up/drop-down feature that will allow an admin to add a fuze to the curated playlist. I made two designs. V1 is takes up the whole screen where as V2 is a drop down on a fuze.

Please review these and approve or make a suggestion on how you'd like this feature to work.

[Version 1](https://sketch.cloud/s/agE1z/nRjvWmV)

[Version 2](https://sketch.cloud/s/agE1z/Qbd2rR1)

**Comment by Spessartine** [comment]
I prefer Version 2.

**Comment by GraysonE** [comment]
Functionality and styles for this was done in #30
