### ISSUE TITLE
Bug - Header missing for "trending" on home page when logged out

### ISSUE THREAD

**Issue by Spessartine** [ErhardLabs/tunefuze#334]
The header and purple line for the "Trending" section of the listen page are missing when user is logged out. Found using Chrome.
![Trending header and purple line missing](https://user-images.githubusercontent.com/50504589/77516747-8665c400-6e40-11ea-887d-c4dc774d0554.JPG)

**Comment by erhardsc** [comment]
@Spessartine any more details you can provide on this issue? Maybe steps to reproduce? I tried reproducing it on my end but haven't gotten the same result

![Screen Shot 2020-05-04 at 2 01 19 PM](https://user-images.githubusercontent.com/17289312/81008240-e07a8180-8e0f-11ea-89c2-5dbc96b9bbef.png)

**Comment by Spessartine** [comment]
The "trending" header is showing up for me now too. Weird, but I'm glad it is there now!
