### ISSUE TITLE
Bug - Master Play button is missing in Edge

### ISSUE THREAD

**Issue by Spessartine** [ErhardLabs/tunefuze#335]
The play button doesn't show up at all when using Microsoft Edge. I tried several different fuzes and the bug affects all of them.
![master play button missing in edge](https://user-images.githubusercontent.com/50504589/77520453-db0c3d80-6e46-11ea-9d9b-432bc6b3ba72.JPG)

**Comment by GraysonE** [comment]
@Spessartine Well this is fun. . . I can't reproduce this on my mac's version of Edge. Can you right click, inspect element, click on "console", and send me a screenshot please?

**Comment by Spessartine** [comment]
![#335 2 - console screenshot](https://user-images.githubusercontent.com/50504589/78087030-ed253900-737c-11ea-858c-4e6dd2014c14.JPG)

**Comment by GraysonE** [comment]
@Spessartine are you sure you're using Edge and not IE? Maybe confirm or re-download Edge and try again. Take a look at the documentation for the createMediaStreamDestination method:
![Screen Shot 2020-04-01 at 8 31 53 PM](https://user-images.githubusercontent.com/7062755/78204851-f9ca8f80-7457-11ea-8266-6376bf7725c6.png)

**Comment by Spessartine** [comment]
I was using a very old vesion of Edge and just updated it. The error went away, but now I am getting a different one. 
![#335 3 - loading error in fuzes - edge](https://user-images.githubusercontent.com/50504589/78717967-a84e5480-78de-11ea-8334-cd8525d06101.JPG)

**Comment by Spessartine** [comment]
The project looks like it is loading and the loading graphic works, but the fuze never gets past the "Loading project..." point.

**Comment by Spessartine** [comment]
Here is the new version of Edge I am using:

Microsoft Edge is up to date.
Version 80.0.361.111 (Official build) (64-bit)

**Comment by Spessartine** [comment]
The XHR error also pops up in Chrome, and pops up for each individual track. It came up 5 times on the "Check out my FUUUU" fuze, which I remember is a 5 track fuze.

**Comment by GraysonE** [comment]
@Spessartine can you try again please?

**Comment by Spessartine** [comment]
Fuzes are working again and the master play button shows up in Edge now. It's fixed!
