### ISSUE TITLE
Bug - main menu is glitched in Edge

### ISSUE THREAD

**Issue by Spessartine** [ErhardLabs/tunefuze#336]
The main menu button is glitched in Edge. Instead of a sandwich menu, it appears as a white block in the middle/top of the page. The search bar is also missing (the top right search bar in the wordpress toolbar works though). When clicking the white block, the sandwich menu functionality appears to still be intact.
![main menu glitched in Edge](https://user-images.githubusercontent.com/50504589/77521331-2115d100-6e48-11ea-9fef-e1e5a34d2101.JPG)

**Comment by GraysonE** [comment]
@erhardsc couldn't replicate in mac microsoft edge. This must be a windows edge bug.

**Comment by Spessartine** [comment]
It is a bug that only affects very old verisions of Edge. I updated to a recent version and the bug went away. I think it is fine to ignore this bug since it doesn't exist in new versions of Edge. Here is the version I am currently using:

Version 80.0.361.111 (Official build) (64-bit)
@GraysonE @erhardsc
