### ISSUE TITLE
Bug - page icon at the top of the "About" page in FireFox

### ISSUE THREAD

**Issue by Spessartine** [ErhardLabs/tunefuze#337]
In FireFox, the About page has a small page icon at the very top of the page, just above the "About Tunefuze" text.
![page icon at top of about page - firefox](https://user-images.githubusercontent.com/50504589/77521770-cfba1180-6e48-11ea-9e55-96b0c4fc3de6.JPG)

**Comment by erhardsc** [comment]
@Spessartine can you try clearing [your browser cache](https://kb.iu.edu/d/ahic) and reloading this page. The tunefuze logo loads fine for me in my version of Firefox

**Comment by Spessartine** [comment]
After clearing my cache it is loading in my version of Firefox as well.
