### ISSUE TITLE
Profile - Settings

### ISSUE THREAD

**Issue by erhardsc** [ErhardLabs/tunefuze#34]
Here are all the designs for the settings page.

[General](https://sketch.cloud/s/agE1z/m19Z0bg)
[Account](https://sketch.cloud/s/agE1z/dlRdPa9)
[Notifications](https://sketch.cloud/s/agE1z/zx4kRMr)
[Export Data](https://sketch.cloud/s/agE1z/ZOEpbzG)

**Comment by Spessartine** [comment]
Looks good! I'll let you know if I think of anything that needs to be added. Is the "Export Data" section for analytics?

**Comment by erhardsc** [comment]
@Spessartine - the export data section is for users to be able to see what all data is stored about them on the site. This is a feature that has been added to membership sites and plugins due to the GDPR regulations that got passed last year.

**Comment by GraysonE** [comment]
I need to make the edit bio and location fields dynamic, not database-based.

**Comment by GraysonE** [comment]
New edit profile strategy:

- [ ] Polish profile photo editing

- [ ] Move general profile edit to new url where we can control the fields and don't need to use the database

- [ ] Cover image polish

**Comment by erhardsc** [comment]
@GraysonE 

I updated the styles for the profile settings page and added styles for the edit profile photo. Please review when you have a chance.

I wasn't able to add styles to the tinymce editor in the General settings tab. With a quick Google search it seems like I have to toggle to styles with JS. I'm not a fan of adding styles through JS and it seems like overkill to add styles through JS.

This is how the tinymce editor looks right now.

![Screen Shot 2019-12-04 at 1 29 02 PM](https://user-images.githubusercontent.com/17289312/70178773-14ebe500-169a-11ea-8d9d-2d1fcfc12ac6.png)
