### ISSUE TITLE
Create - Settings Slide Out

### ISSUE THREAD

**Issue by erhardsc** [ErhardLabs/tunefuze#36]
MVP will only have privacy settings and bounce feature

[Settings slide out](https://sketch.cloud/s/agE1z/dlRdPOb)

**Comment by erhardsc** [comment]
@GraysonE - Do you think we'll be able to use our already built slideout sidebar for the slide out? I have an implementation currently working. Just need to know if you think adding the settings or other content in is feasible

**Comment by erhardsc** [comment]
@GraysonE - It would be cool if each section in the slideout sidebar had a dynamic class added to it so that styling could be more targeted

![Screenshot 2019-05-30 19 09 11](https://user-images.githubusercontent.com/17289312/58674777-98550400-830e-11e9-823f-4f2947651a58.png)

**Comment by erhardsc** [comment]
@GraysonE another possible option for building this out would be to use a widget for the settings

**Comment by GraysonE** [comment]
@erhardsc ready for your styles. I will work on functionality after everything looks the way it should.

**Comment by erhardsc** [comment]
@GraysonE styles have been added and is ready for functionality

**Comment by GraysonE** [comment]
@erhardsc all functionality works, just needs some touching up with front end.
