### ISSUE TITLE
Misc. Pages & Support Articles

### ISSUE THREAD

**Issue by erhardsc** [ErhardLabs/tunefuze#37]
We will need a default page design for these pages

Docs & Support - archive blog posts
Creating a Fuze - single blog posts

**Comment by erhardsc** [comment]
@Spessartine & @GraysonE  - Let me know what you'd like for me to include in the About page. Obviously there should be a paragraph or two about the history behind this project, but are there any other items like a grid display of the team or a place for photos?

**Comment by erhardsc** [comment]
Designs are below

[About](https://sketch.cloud/s/agE1z/a/o01AE0)

[Docs & Support](https://sketch.cloud/s/agE1z/a/Rndwre)

[Single Support Article](https://sketch.cloud/s/agE1z/a/1ZLgo8)

**Comment by erhardsc** [comment]
Increase line height and text spacing

**Comment by erhardsc** [comment]
Steps to set this feature up on your install.

- Create a new category called "Support"
- Create a new page called "Docs & Support" and assign it the page template "tunefuze-support"

**Comment by GraysonE** [comment]
@erhardsc needs max width
