### ISSUE TITLE
Update BuddyPress and test

### ISSUE THREAD

**Issue by GraysonE** [ErhardLabs/tunefuze#384]

**Comment by erhardsc** [comment]
@GraysonE 

I updated the plugin and here's what I tested, Which is basically the test from the wiki. Let me know if I missed anything!

# Owner
## Fuzes

- [X] Fuzes load

- [X] Fuzes paginate

- [X] Create fuze works

- [X] Fuze dropdown settings work - See "Individual Fuze Dropdown Settings"

- [X] Change profile works

## Notifications

- [X] Bulk actions work

- [X] Links redirect user

- [X] Links mark notifications as read

- [X]  Read notifications load

- [X]  Read notification bulk actions work

- [X]  Change profile works

## About
- [X]  Stats are accurate
- [X]  Bio and Stats load
- [X]  Change profile works

## Edit Profile
- [X]  General settings save
- [X]  Notification settings save
- [X]  Account settings save
- [X]  Data export settings
- [X]  Change profile works
- [X]  Account Creation
- [X]  Account Deletion

## Followers

- [X] Unfollow works

- [X] Change profile works

## Following

- [X] Unfollow works

- [X] Change profile works

# Viewer 
## Fuzes

- [X] Unfollow works

- [X] Recently Created fuzes load

- [X] Admins can access fuze dropdown settings

- [X] Liked fuzes load

- [X] Pagination works

## About

- [X] Bio loads

- [X] Stats load

**Comment by GraysonE** [comment]
If you tested all of that, close it.
