### ISSUE TITLE
Update & remove duplicate jquery version to remove security vulnerabilities

### ISSUE THREAD

**Issue by GraysonE** [ErhardLabs/tunefuze#387]
See below from lighthouse audit:
![Screen Shot 2020-05-27 at 7 12 25 PM](https://user-images.githubusercontent.com/7062755/83087245-04fffd00-a04e-11ea-9411-438921ae4155.png)

**Comment by erhardsc** [comment]
@GraysonE I'm getting different lighthouse results. This is from live and on my local environment

<img width="704" alt="Screen Shot 2020-06-08 at 1 58 17 PM" src="https://user-images.githubusercontent.com/17289312/84074725-33f06a00-a990-11ea-8719-a94ea816446a.png">
