### ISSUE TITLE
Create Account

### ISSUE THREAD

**Issue by erhardsc** [ErhardLabs/tunefuze#43]
This page needs styles

http://tunefuze.test/register/

**Comment by GraysonE** [comment]
- [ ] Redirect logged in users

**Comment by GraysonE** [comment]
@erhardsc 

- [ ] Style wysiwyg

- [ ] Better spacing between headers and fields

- [ ] Terms and conditions checkbox not aligned with text

**Comment by GraysonE** [comment]
wp-content/plugins/buddypress/bp-members/screens/register.php

**Comment by GraysonE** [comment]
@erhardsc

![Screen Shot 2019-12-11 at 7 16 40 PM](https://user-images.githubusercontent.com/7062755/70676869-cb2b6d80-1c4a-11ea-9341-b662ff5e595d.png)

**Comment by GraysonE** [comment]
@erhardsc after taking out the inner join it fixed a scenario where it was displaying the same user twice in the results. I think we should leave it out.

**Comment by GraysonE** [comment]
@erhardsc this is on your plate now. I made my changes in issue_43.2. Please delete the plugin "Redirect after Login." It is buggy.

**Comment by GraysonE** [comment]
@erhardsc I also deactivated WooCommerce for now. Please do the same.

**Comment by erhardsc** [comment]
@GraysonE I updated the styles for the create account page. I didn't check off the wysiwyg styles because I was unsure what you meant by that or where exactly that is on the page.

**Comment by erhardsc** [comment]
@GraysonE  Please go through the account registration process and let me know if you run into any of these errors
![Screen Shot 2020-01-16 at 10 41 09 AM](https://user-images.githubusercontent.com/17289312/72548820-bdba6200-384c-11ea-9641-406878bc3bcb.png)
