### ISSUE TITLE
Individual track number of iterations textbox and plus/minus buttons

### ISSUE THREAD

**Issue by GraysonE** [ErhardLabs/tunefuze#68]
In the create page under track settings, add another setting that allows a user to loop the track but also have a max number of iterations that the track should play for.

Plus and minus buttons to change the number of iterations

Text box displays the number of iterations. Same as speed

**Comment by erhardsc** [comment]
@GraysonE track iteration html has been added but the functionality and values inside the html will need to be updated

**Comment by erhardsc** [comment]
@GraysonE 

- [ ] change wording to "loop"

- [ ] add 'x' to number

**Comment by GraysonE** [comment]
- [ ] User source.loop property. source.loop = 1
https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/loop

- [ ] increment a value every time the loopEnd property is reached: 
https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/loopEnd

- [ ]  if loop incremented value reaches saved db loop value for that track, kill the loop. source.loop = 0
