### ISSUE TITLE
Administration Email Verification styles

### ISSUE THREAD

**Issue by GraysonE** [ErhardLabs/tunefuze#78]

**Comment by erhardsc** [comment]
@GraysonE The email verifiaction screen popped up for me again so I went ahead and did some basic styles for it.

Here's what it looks like now
![Screen Shot 2020-01-16 at 10 51 29 AM](https://user-images.githubusercontent.com/17289312/72549632-4a195480-384e-11ea-9a07-6b69997ad665.png)
